"""Export a quantised model (and a sample input) to C headers.

The microcontroller side has no Python and no file system to speak of, so the
model is baked straight into the firmware as ``const`` arrays. This module
writes two headers:

* ``model_data.h`` - the int8 weights, their float scales, the float biases and
  the layer dimensions.
* ``sample.h`` - one example feature vector plus its true label, so the C
  program has something to classify out of the box.

The arrays are laid out exactly how ``c/kws_infer.c`` expects them
(row-major, ``W[in][out]`` flattened to ``W[i * out + o]``).
"""

from __future__ import annotations

import numpy as np

from .quantize import QuantMLP


def _c_float(v: float) -> str:
    """Format a float as a valid C ``float`` literal.

    ``%g`` can emit bare integers like ``0`` or ``3``; appending ``f`` to those
    would read as an (invalid) octal constant, so we guarantee a decimal point
    or exponent is present before the suffix.
    """
    s = f"{float(v):.8g}"
    if not any(c in s for c in ".eEnN"):   # no '.', exponent, or inf/nan
        s += ".0"
    return s + "f"


def _c_array(name: str, values, ctype: str) -> str:
    """Render a flat numeric array as a C definition."""
    flat = np.asarray(values).reshape(-1)
    if ctype == "float":
        items = ", ".join(_c_float(v) for v in flat)
    else:
        items = ", ".join(str(int(v)) for v in flat)
    return f"static const {ctype} {name}[{flat.size}] = {{{items}}};"


def write_model_header(qmodel: QuantMLP, labels: list[str], path: str) -> None:
    in_dim, hidden = qmodel.qW1.shape
    n_classes = qmodel.qW2.shape[1]
    labels_c = ", ".join(f'"{name}"' for name in labels)

    lines = [
        "/* Auto-generated by kws.export - do not edit by hand. */",
        "#ifndef KWS_MODEL_DATA_H",
        "#define KWS_MODEL_DATA_H",
        "",
        f"#define KWS_IN_DIM    {in_dim}",
        f"#define KWS_HIDDEN    {hidden}",
        f"#define KWS_N_CLASSES {n_classes}",
        "",
        f"static const char *KWS_LABELS[KWS_N_CLASSES] = {{{labels_c}}};",
        "",
        "/* Layer 1: input -> hidden (row-major [in][hidden]). */",
        _c_array("KWS_W1", qmodel.qW1, "signed char"),
        f"static const float KWS_S1 = {_c_float(qmodel.sW1)};",
        _c_array("KWS_B1", qmodel.b1, "float"),
        "",
        "/* Layer 2: hidden -> classes (row-major [hidden][classes]). */",
        _c_array("KWS_W2", qmodel.qW2, "signed char"),
        f"static const float KWS_S2 = {_c_float(qmodel.sW2)};",
        _c_array("KWS_B2", qmodel.b2, "float"),
        "",
        "#endif /* KWS_MODEL_DATA_H */",
        "",
    ]
    with open(path, "w") as f:
        f.write("\n".join(lines))


def write_sample_header(feature: np.ndarray, label_index: int,
                        labels: list[str], path: str) -> None:
    lines = [
        "/* Auto-generated by kws.export - one example feature vector. */",
        "#ifndef KWS_SAMPLE_H",
        "#define KWS_SAMPLE_H",
        "",
        f"#define KWS_TRUE_LABEL {label_index}  /* {labels[label_index]} */",
        "",
        _c_array("KWS_SAMPLE", feature, "float"),
        "",
        "#endif /* KWS_SAMPLE_H */",
        "",
    ]
    with open(path, "w") as f:
        f.write("\n".join(lines))
